[#ftl]
[@b.head/]
[@b.grid items=salesOrders var="salesOrder"]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="5%" property="customer.code" title="顾客"]${salesOrder.customer.code}[/@]
    [@b.col width="8%" property="code" title="订单编号"][@b.a href="sales-order!info?id=${salesOrder.id}"]${salesOrder.code}[/@][/@]
    [@b.col width="10%" property="product.code" title="产品图号"]${salesOrder.product.specification!}[/@]
    [@b.col width="5%" property="orderType.name" title="订单类型"/]
    [@b.col width="8%" property="deadline" title="客户交期"]${(salesOrder.deadline?string("yyyy-MM-dd"))!}[/@]

    [@b.col width="8%" property="plannedEndOn" title="计划交期"/]
    [@b.col width="8%" property="batchNum" title="生产批号"/]
    [@b.col width="5%" property="amount" title="计划数量"/]

    [@b.col width="7%" property="materialDate" title="到料日期"]${(salesOrder.materialDate?string("MM-dd"))!}[/@]
    [@b.col width="20%" title="生产周期评估"]
      [#assign assessMap={}]
      [#list salesOrder.assesses as assess]
        [#assign departId=assess.technic.depart.id?string/]
        [#assign assessMap=assessMap+{departId:(assess.days + (assessMap[departId]!0))}]
      [/#list]
      [#assign departs= []/]
      [#list salesOrder.technicScheme.technics as pt]
        [#if !departs?seq_contains(pt.technic.depart)]
           [#assign departs= departs+[pt.technic.depart]/]
        [/#if]
      [/#list]
      <div class="btn-group btn-group-sm" role="group">
      [#list departs as depart]
       [@b.a class="btn btn-primary" style="font-size:0.8em" href="!assess?salesOrderId=${salesOrder.id}&departId=${depart.id}"]${depart.name} ${assessMap[depart.id?string]!}[/@]
      [/#list]
     </div>
    [/@]
    [@b.col width="6%" property="status.name" title="订单状态"/]
  [/@]
[/@]
[@b.foot/]
