[#ftl]
[@b.head/]
[@b.toolbar title="厂区基本信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(factory) theme="list"]
    [@b.textfield name="factory.code" label="编码" value="${factory.code!}" required="true" maxlength="10"/]
    [@b.textfield name="factory.name" label="名称" value="${factory.name!}" required="true" maxlength="80"/]
    [@b.textfield name="factory.address" label="地址" value="${factory.address!}" required="true" /]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
