[#ftl]
[@b.head/]
[@b.toolbar title="修改产品信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(material) theme="list"]
    [@b.textfield name="material.code" label="产品图号" value="${material.code!}" required="true" maxlength="30"/]
    [@b.textfield name="material.name" label="产品名称" value="${material.name!}" required="true" maxlength="80"/]
    [@b.textfield name="material.standard" label="规格" value="${material.standard!}" required="true" maxlength="80"/]
    [@b.select name="material.materialType.id" label="品号类别" value="${(material.materialType.id)!}" required="true"  style="width:200px;" items=materialTypes empty="..." option=r"${item.code}${item.name}" /]
    [@b.textfield name="material.remark" label="备注" value="${material.remark!}" maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]

[@b.foot/]
