[#ftl]
[@b.head/]
<script language="JavaScript" type="text/JavaScript" src="${base}/static/js/ajax-chosen.js"></script>
[@b.toolbar title="修改客户信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(customer) theme="list"]
    [@b.textfield name="customer.code" label="编号" value="${customer.code!}" required="true" maxlength="30"/]
    [@b.textfield name="customer.name" label="姓名" value="${customer.name!}" required="true" maxlength="80"/]
[#--    [@b.field label="业务人员" required='true']--]
[#--    <select id="salers" name="customer.salers" style="width:200px;" multiple="true">--]
[#--      [#list (customer.salers)! as saler]--]
[#--        <option value='${saler.id}' selected>${saler.name}(${saler.code})</option>--]
[#--      [/#list]--]
[#--    </select>--]
[#--    [/@]--]
    [@b.select2 label="业务人员" name1st="salerId1st" name2nd="salerId2nd" style = "height:80px;width:152px"
    items1st=users items2nd= customer.salers option=r"${item.code}${item.name}"  required="true" /]
    [@b.textfield name="customer.mobile" label="电话" value="${customer.mobile!}" maxlength="15"/]
    [@b.textfield name="customer.email" label="邮箱" value="${customer.email!}"  maxlength="80"/]
    [@b.textfield name="customer.remark" label="备注" value="${customer.remark!}" maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]

[#--<script>--]
[#--  jQuery(function() {--]
[#--    jQuery("#salers").ajaxChosen(--]
[#--            {--]
[#--              method: 'POST',--]
[#--              url: '${b.url("customer!salerAjax")}',--]
[#--              postData:function(){--]
[#--                return {--]
[#--                  pageIndex:1,--]
[#--                  pageSize:10,--]
[#--                }--]
[#--              }--]
[#--            }--]
[#--            , function(data) {--]
[#--              var dataObj=eval("(" + data + ")");--]
[#--              var items = {};--]
[#--              jQuery.each(dataObj.users, function(i, user) {--]
[#--                items[user.code] = user.name + '(' + user.code + ')';--]
[#--              });--]
[#--              return items;--]
[#--            });--]

[#--  })--]
[#--</script>--]
[@b.foot/]
