[#ftl]
[@b.head/]
<script language="JavaScript" type="text/JavaScript" src="${base}/static/js/ajax-chosen.js"></script>
[@b.toolbar title="修改客户信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(customer) theme="list"]
    [@b.textfield name="customer.code" label="客户编号" value="${customer.code!}" required="true" maxlength="30"/]
    [@b.textfield name="customer.name" label="客户名称" value="${customer.name!}" required="true" maxlength="80"/]
    [@b.select label="业务人员" name1st="customer.saler.id"  items=users  option=r"${item.code}${item.name}" required="false" /]
    [@b.textfield name="customer.quickCode" label="快捷码" value="${customer.quickCode!}" maxlength="5"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]

[#--<script>--]
[#--  jQuery(function() {--]
[#--    jQuery("#salers").ajaxChosen(--]
[#--            {--]
[#--              method: 'POST',--]
[#--              url: '${b.url("customer!salerAjax")}',--]
[#--              postData:function(){--]
[#--                return {--]
[#--                  pageIndex:1,--]
[#--                  pageSize:10,--]
[#--                }--]
[#--              }--]
[#--            }--]
[#--            , function(data) {--]
[#--              var dataObj=eval("(" + data + ")");--]
[#--              var items = {};--]
[#--              jQuery.each(dataObj.users, function(i, user) {--]
[#--                items[user.code] = user.name + '(' + user.code + ')';--]
[#--              });--]
[#--              return items;--]
[#--            });--]

[#--  })--]
[#--</script>--]
[@b.foot/]
