[#ftl]
[@b.head/]
[@b.toolbar title="编辑到料日期"]bar.addBack();[/@]
  [@b.form action=b.rest.save(workOrder) theme="list"]
    [@b.field label="工单编号"]${workOrder.code}[/@]
    [@b.field label="生产批号"]${workOrder.batchNum}[/@]
    [@b.field label="产品图号"]${workOrder.product.code}[/@]
    [@b.field label="工单数量"]${workOrder.amount}[/@]
    [@b.field label="客户交期"]${workOrder.deadline?string("yyyy-MM-dd")}[/@]
    [@b.field label="计划交期"]${(workOrder.plannedEndOn?string("yyyy-MM-dd"))!}[/@]
    [@b.field label="工单备注"]${(workOrder.remark)?default("无")}[/@]
    [@b.datepicker name="workOrder.materialDate" label="到料日期" value=(workOrder.materialDate)! maxDate="${workOrder.deadline?string('yyyy-MM-dd')}"  required="true"  format="yyyy-MM-dd" /]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
