[#ftl]
[@b.head/]
[@b.toolbar title="编辑到料日期"]bar.addBack();[/@]
  [@b.form action=b.rest.save(workOrder) theme="list"]
    [@b.field label="订单编号"]${workOrder.salesOrderNo}[/@]
    [@b.field label="生产批号"]${workOrder.batchNum}[/@]
    [@b.field label="产品图号"]${workOrder.product.code}[/@]
    [@b.field label="工单数量"]${workOrder.amount}[/@]
    [@b.field label="客户交期"]${workOrder.deadline?string("yyyy-MM-dd")}[/@]
    [@b.field label="计划交期"]${(workOrder.plannedEndOn?string("yyyy-MM-dd"))!}[/@]
    [@b.field label="材料清单"]
      [#list workOrder.product.bom as i]${i.material.name} ${i.material.specification!} [#if i.amount??]${i.amount*workOrder.amount} ${i.material.unit.name}[#else]??[/#if][#if i_has_next]<br>[/#if][/#list]
    [/@]
    [@b.field label="工单备注"]${(workOrder.remark)?default("无")}[/@]
    [@b.radios label="是否有料" name="materialAssess.ready" value=materialAssess.ready!/]
    [@b.datepicker name="materialAssess.readyOn" label="到料日期" value=(materialAssess.readyOn)! minDate="${b.now?string('yyyy-MM-dd')}" maxDate="${workOrder.deadline?string('yyyy-MM-dd')}" format="yyyy-MM-dd" /]
    [@b.formfoot]
      <input type="hidden" name="materialAssess.id" value="${materialAssess.id!}"/>
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
