[#ftl]
[@b.head/]
[@b.grid items=workOrders var="workOrder"]
  [@b.gridbar]
    bar.addItem("${b.text("编辑到料日期")}",action.edit());
    bar.addItem("${b.text("action.export")}",action.exportData("orderType.name:工单单别,batchNum:工单单号,product.code:品号,product.specification:公司图号,technicScheme.name:工单工艺,amount:数量,deadline:客户交付日期,plannedEndOn:计划交付日期,scheduledOn:评审交付日期,status.name:工单状态,assessStatus:评审状态,materialAssess.ready:是否有料,materialAssess.readyOn:到料日期,factory.name:工厂,createdAt:创建日期",null,'fileName=工单信息'));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="10%" property="batchNum" title="工单单号"]
      [@b.a href="!info?id=${workOrder.id}" title="${workOrder.orderType.code} ${workOrder.orderType.name}"]${workOrder.batchNum}[/@]
    [/@]
    [@b.col width="15%" property="product.code" title="产品图号"]${workOrder.product.specification!}[/@]
    [@b.col width="7%" property="deadline" title="客户交期"]${(workOrder.deadline?string("yy-MM-dd"))!}[/@]
    [@b.col width="6%" property="amount" title="数量"/]
    [@b.col width="27%"  title="材料"]
       [#list workOrder.product.bom as i]${i.material.name} ${i.material.specification!} [#if i.amount??]${i.amount*workOrder.amount} ${i.material.unit.name}[#else]??[/#if][#if i_has_next]<br>[/#if][/#list]
    [/@]
    [@b.col width="7%" title="到料日期"] [#if workOrder.materialAssess??] [#if workOrder.materialAssess.ready]有料[#else] ${(workOrder.materialAssess.readyOn?string("yy-MM-dd"))!}[/#if][/#if][/@]
    [@b.col width="7%" title="操作日期"]
     [#if workOrder.materialAssess??]
      <span title="${(workOrder.materialAssess.assessedBy.name)!}">${workOrder.materialAssess.updatedAt?string("yy-MM-dd")}</span>
     [/#if]
    [/@]
    [@b.col width="8%" property="assessStatus" title="评审状态"]${workOrder.assessStatus.name} [#if workOrder.assessStatus.name=="复审中"]${workOrder.reviewEvents?size}[/#if][/@]
    [@b.col width="8%" property="status.name" title="工单状态"/]
  [/@]
[/@]
[@b.foot/]
