[#ftl]
[@b.head/]
[@b.toolbar title="工单单别"]bar.addBack();[/@]
  [@b.form action=b.rest.save(workOrderType) theme="list"]
    [@b.textfield name="workOrderType.code" label="代码" value="${workOrderType.code!}" required="true" maxlength="10"/]
    [@b.textfield name="workOrderType.name" label="名称" value="${workOrderType.name!}" required="true" maxlength="80"/]
    [@b.textfield name="workOrderType.remark" label="备注" value="${workOrderType.remark!}" maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
