[#ftl]
[@b.head/]
[@b.toolbar title="工单类型"]bar.addBack();[/@]
  [@b.form action=b.rest.save(orderType) theme="list"]
    [@b.textfield name="orderType.code" label="代码" value="${orderType.code!}" required="true" maxlength="10"/]
    [@b.textfield name="orderType.name" label="名称" value="${orderType.name!}" required="true" maxlength="80"/]
    [@b.textfield name="orderType.remark" label="备注" value="${orderType.remark!}" maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
