[#ftl]
[@b.head/]
[@b.grid items=workOrders var="workOrder"]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="8%" property="batchNum" title="工单单号"]
       [@b.a href="work-order!info?id=${workOrder.id}" title="${workOrder.orderType.code} ${workOrder.orderType.name}"]${workOrder.batchNum}[/@]
    [/@]
    [@b.col width="15%" property="product.code" title="产品图号"]${workOrder.product.specification!}[/@]
    [@b.col width="8%" property="deadline" title="客户交期"]${(workOrder.deadline?string("yy-MM-dd"))!}[/@]
    [@b.col width="8%" property="plannedEndOn" title="计划交期"]${(workOrder.plannedEndOn?string("yy-MM-dd"))!}[/@]
    [@b.col width="5%" property="amount" title="数量"/]

    [@b.col width="8%" property="materialDate" title="到料日期"]
      [#if workOrder.materialAssess??][#if workOrder.materialAssess.ready]有料[#else] ${(workOrder.materialAssess.readyOn?string("yy-MM-dd"))!}[/#if][/#if]
    [/@]
    [@b.col width="29%" title="生产周期评估"]
      [#assign assessMap={}]
      [#list workOrder.technics as wt]
        [#if wt.technic.assessGroup?? && wt.days??]
        [#assign assessGroupId=wt.technic.assessGroup.id?string/]
        [#assign assessMap=assessMap+{assessGroupId:(wt.days + (assessMap[assessGroupId]!0))}]
        [/#if]
      [/#list]
      [#assign assessGroups= []/]
      [#assign cannotAssessed= []/]
      [#list workOrder.technics as wt]
        [#if wt.technic.assessGroup??]
          [#if !assessGroups?seq_contains(wt.technic.assessGroup)]
             [#assign assessGroups = assessGroups+[wt.technic.assessGroup]/]
          [/#if]
        [#else]
           [#assign cannotAssessed = cannotAssessed + [wt.technic]/]
        [/#if]
      [/#list]
    [#if workOrder.canAssess && cannotAssessed?size=0]
      [#assign btnClz][#if workOrder.inReview]btn btn-warning[#else]btn btn-info[/#if][/#assign]
      <div class="btn-group btn-group-sm" role="group">
      [#list assessGroups as assessGroup]
       [#if assessMap[assessGroup.id?string]??]
         [#if myGroups?seq_contains(assessGroup)]
           [@b.a class=btnClz style="font-size:0.8em" href="!assess?workOrderId=${workOrder.id}&assessGroupId=${assessGroup.id}"]${assessGroup.name} ${assessMap[assessGroup.id?string]}[/@]
         [#else]
           <button class="${btnClz}" style="font-size:0.8em">${assessGroup.name} ${assessMap[assessGroup.id?string]}</button>
         [/#if]
       [#else]
         [#if myGroups?seq_contains(assessGroup)]
           [@b.a class="btn btn-primary" style="font-size:0.8em" href="!assess?workOrderId=${workOrder.id}&assessGroupId=${assessGroup.id}"]${assessGroup.name}[/@]
         [#else]
           <button class="btn btn-primary" style="font-size:0.8em">${assessGroup.name}</button>
         [/#if]
       [/#if]
      [/#list]
     </div>
   [#else]
      [#if cannotAssessed?size>0 ]
         缺少评审设置:[#list cannotAssessed as t ]${t.name}&nbsp;[/#list]
      [#else]
        [#assign btnClz][#if workOrder.inReview]btn btn-warning[#else]btn btn-success[/#if][/#assign]
        <div class="btn-group btn-group-sm" role="group">
        [#list assessGroups as assessGroup]
         [#if assessMap[assessGroup.id?string]??]
           <button class="${btnClz}" style="font-size:0.8em">${assessGroup.name} ${assessMap[assessGroup.id?string]}</button>
         [#else]
           <button class="btn btn-primary" style="font-size:0.8em">${assessGroup.name}</button>
         [/#if]
        [/#list]
       </div>
      [/#if]
   [/#if]
    [/@]
    [@b.col width="8%" property="status.name" title="工单状态"/]
    [@b.col width="7%" property="assessStatus" title="评审状态"]${workOrder.assessStatus.name}[/@]
  [/@]
[/@]
[@b.foot/]
