[#ftl]
[@b.head/]
[@b.grid items=workOrders var="workOrder"]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="5%" property="customer.code" title="顾客"]${workOrder.customer.code}[/@]
    [@b.col width="8%" property="code" title="工单编号"][@b.a href="work-order!info?id=${workOrder.id}"]${workOrder.code}[/@][/@]
    [@b.col width="10%" property="product.code" title="产品图号"]${workOrder.product.specification!}[/@]
    [@b.col width="5%" property="orderType.name" title="工单类型"/]
    [@b.col width="8%" property="deadline" title="客户交期"]${(workOrder.deadline?string("yyyy-MM-dd"))!}[/@]

    [@b.col width="8%" property="plannedEndOn" title="计划交期"/]
    [@b.col width="8%" property="batchNum" title="生产批号"/]
    [@b.col width="5%" property="amount" title="计划数量"/]

    [@b.col width="7%" property="materialDate" title="到料日期"]${(workOrder.materialDate?string("MM-dd"))!}[/@]
    [@b.col width="20%" title="生产周期评估"]
      [#assign assessMap={}]
      [#list workOrder.assesses as assess]
        [#assign departId=assess.technic.depart.id?string/]
        [#assign assessMap=assessMap+{departId:(assess.days + (assessMap[departId]!0))}]
      [/#list]
      [#assign departs= []/]
      [#list workOrder.technicScheme.technics as pt]
        [#if !departs?seq_contains(pt.technic.depart)]
           [#assign departs= departs+[pt.technic.depart]/]
        [/#if]
      [/#list]
      <div class="btn-group btn-group-sm" role="group">
      [#list departs as depart]
       [#if assessMap[depart.id?string]??]
         [@b.a class="btn btn-info" style="font-size:0.8em" href="!assess?workOrderId=${workOrder.id}&departId=${depart.id}"]${depart.name} ${assessMap[depart.id?string]}[/@]
       [#else]
         [@b.a class="btn btn-primary" style="font-size:0.8em" href="!assess?workOrderId=${workOrder.id}&departId=${depart.id}"]${depart.name}[/@]
       [/#if]
      [/#list]
     </div>
    [/@]
    [@b.col width="6%" property="status.name" title="工单状态"/]
  [/@]
[/@]
[@b.foot/]
