[#ftl]
[@b.head/]
[@b.toolbar title="产品材料清单基本信息"]bar.addBack();[/@]
  [@b.form action=b.rest.save(item) theme="list"]
    [@b.field label="产品"]${product.code} ${product.name} ${product.specification!}[/@]
    [@b.textfield name="item.indexno" label="顺序号" value=item.indexno! /]
    [@b.select name="item.material.id" label="材料"  value=item.material! option="id,title" href="/base/materials.json?q={term}" empty="..." required="true"/]
    [@b.textfield name="item.amount" label="数量" value="${item.amount!}" /]
    [@b.formfoot]
      <input type="hidden" value="${product.id}" name="item.product.id"/>
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
