[#ftl]
[@b.head/]
[@b.toolbar title="编辑到料日期"]bar.addBack();[/@]
  [@b.form action=b.rest.save(salesOrder) theme="list"]
    [@b.field label="订单编号"]${salesOrder.code}[/@]
    [@b.field label="生产批号"]${salesOrder.batchNum}[/@]
    [@b.field label="产品图号"]${salesOrder.product.code}[/@]
    [@b.field label="订单数量"]${salesOrder.count}[/@]
    [@b.field label="计划交付日期"]${salesOrder.requireOn?string("yyyy-MM-dd")}[/@]
    [@b.field label="订单备注"]${(salesOrder.remark)?default("无")}[/@]
    [@b.datepicker name="salesOrder.materialDate" label="到料日期" value=(salesOrder.materialDate)! maxDate="${salesOrder.requireOn?string('yyyy-MM-dd')}"  required="true"  format="yyyy-MM-dd" /]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[@b.foot/]
