[#ftl]
[@b.head/]
[@b.grid items=salesOrders var="salesOrder"]
  [@b.gridbar]
    bar.addItem("${b.text("编辑到料日期")}",action.edit());
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="5%" property="customer.code" title="顾客"]${salesOrder.customer.code}[/@]
    [@b.col width="10%" property="code" title="订单编号"][@b.a href="!info?id=${salesOrder.id}"]${salesOrder.code}[/@][/@]
    [@b.col width="15%" property="product.code" title="产品图号"]${salesOrder.product.specification!}[/@]
    [@b.col width="5%" property="orderType.name" title="订单类型"/]
    [@b.col width="10%" property="requireOn" title="交期"]${(salesOrder.requireOn?string("yyyy-MM-dd"))!}[/@]

    [@b.col width="10%" property="scheduledOn" title="计划交期"/]
    [@b.col width="10%" property="batchNum" title="生产批号"/]
    [@b.col width="8%" property="count" title="计划数量"/]

    [@b.col width="10%" property="materialDate" title="到料日期"]${(salesOrder.materialDate?string("yyyy-MM-dd"))!}[/@]
    [@b.col width="7%" property="status.name" title="订单状态"/]
  [/@]
[/@]
[@b.foot/]
