[#ftl]
[@b.head/]
[@b.grid items=salesOrders var="salesOrder"]
  [@b.gridbar]
    bar.addItem("${b.text("编辑到料日期")}",action.edit());
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="20%" property="code" title="订单编号"][@b.a href="!info?id=${salesOrder.id}"]${salesOrder.code}[/@][/@]
    [@b.col width="20%" property="batchNum" title="生产批号"/]
    [@b.col width="20%" property="orderType.name" title="订单类型"/]
    [@b.col width="20%" property="product.customer.code" title="顾客代码"/]
    [@b.col width="20%" property="product.code" title="产品图号"/]
    [@b.col width="20%" property="count" title="订单数量"/]
    [@b.col width="20%" property="requireOn" title="计划交付日期"]${(salesOrder.requireOn?string("yyyy-MM-dd"))!}[/@]
    [@b.col width="20%" property="materialDate" title="到料日期"]${(salesOrder.materialDate?string("yyyy-MM-dd"))!}[/@]
    [@b.col width="20%" property="status.name" title="订单状态"/]
  [/@]
[/@]
[@b.foot/]
