[#ftl]
[@b.head/]
[@b.grid items=salesOrders var="salesOrder"]
  [@b.gridbar]
    bar.addItem("${b.text("编辑到料日期")}",action.edit());
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="5%" property="customer.code" title="顾客"]${salesOrder.customer.code}[/@]
    [@b.col width="10%" property="code" title="订单编号"][@b.a href="!info?id=${salesOrder.id}"]${salesOrder.code}[/@][/@]
    [@b.col width="15%" property="product.code" title="产品图号"]${salesOrder.product.specification!}[/@]
    [@b.col width="5%" property="orderType.name" title="订单类型"/]
    [@b.col width="10%" property="deadline" title="客户交期"]${(salesOrder.deadline?string("yyyy-MM-dd"))!}[/@]
    [@b.col width="8%" property="amount" title="计划数量"/]
    [@b.col width="20%"  title="材料"]
      [#list salesOrder.product.bom as i]${i.material.name} ${i.material.specification!} [#if i.material.amount??]${i.material.amount*salesOrder.amount} ${salesOrder.product.unit.name}[#else]??[/#if][#if i_has_next]<br>[/#if][/#list]
    [/@]
    [@b.col width="10%" property="materialDate" title="到料日期"]${(salesOrder.materialDate?string("yyyy-MM-dd"))!}[/@]
    [@b.col width="7%" property="status.name" title="订单状态"/]
  [/@]
[/@]
[@b.foot/]
