[#ftl]
[@b.head/]
[@b.toolbar title="修改产品信息"]bar.addBack();[/@]
[@b.tabs]
  [@b.form action=b.rest.save(product) theme="list"]
    [@b.textfield name="product.code" label="产品编号" value="${product.code!}" required="true" maxlength="30"/]
    [@b.textfield name="product.specification" label="产品图号" value=product.specification!  required="true" maxlength="80"/]
    [@b.textfield name="product.name" label="产品名称" value="${product.name!}" required="true" maxlength="80"/]
    [@b.textfield name="product.remark" label="备注" value="${product.remark!}" maxlength="190"/]
    [@b.formfoot]
      [@b.reset/]&nbsp;&nbsp;[@b.submit value="action.submit"/]
    [/@]
  [/@]
[/@]

[@b.foot/]
