[#ftl]
[@b.head/]
[@b.grid items=products var="product"]
  [@b.gridbar]
    bar.addItem("${b.text("action.new")}",action.add());
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="20%" property="code" title="产品图号"/]
    [@b.col width="20%" property="name" title="产品名称"][@b.a href="!info?id=${product.id}"]${product.name}[/@][/@]
    [@b.col width="20%" property="standard" title="规格"/]
    [@b.col width="20%" property="department" title="客户"]${(product.customer.code)!} ${(product.customer.shortName)!}[/@]
    [@b.col width="20%" property="" title="工艺列表"]
      [#list product.technics! as technic]
        ${(technic.code)!} ${(technic.name)!}[#if technic_has_next],[/#if]
      [/#list]
    [/@]
  [/@]
[/@]
[@b.foot/]
